---
# 1) HelmRepository sources Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-sources
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# 2) Infrastructure Kustomization (depends on the sources)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-sources
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: elasticsearch-master
      namespace: efk-monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: kibana-kibana
      namespace: efk-monitoring
    - apiVersion: apps/v1
      kind: DaemonSet
      name: fluent-bit
      namespace: efk-monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus-prometheus-kube-prometheus-prometheus
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: alertmanager-prometheus-kube-prometheus-alertmanager
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-grafana
      namespace: monitoring
