daemonset:
  enabled: true
tolerations: []

image:
  repository: fluent/fluent-bit
  tag: 3.2.10
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# If you had certs, you'd define them here, but let's keep them out for now
extraVolumes: []
extraVolumeMounts: []

config:
  service: |
    [SERVICE]
        Daemon              Off
        Flush               1
        Log_Level           info
        Parsers_File        /fluent-bit/etc/parsers.conf
        HTTP_Server         On
        HTTP_Listen         0.0.0.0
        HTTP_Port           2020
        Health_Check        On
        storage.path        /var/log/flb-storage/
        storage.sync        normal
        storage.checksum    off
        storage.backlog.mem_limit 5M

  inputs: |
    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        multiline.parser    docker, cri
        Tag                 kube.*
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        Refresh_Interval    5
        storage.type        filesystem
        DB                  /var/log/flb_kube.db

    [INPUT]
        Name                systemd
        Tag                 host.kubelet
        Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail      On
        storage.type        filesystem

    [INPUT]
        Name                tail
        Path                /var/log/messages
        Tag                 host.messages
        Skip_Long_Lines     On
        Refresh_Interval    5
        storage.type        filesystem
        DB                  /var/log/flb_system.db

    [INPUT]
        Name                tail
        Path                /var/log/syslog
        Tag                 host.syslog
        Skip_Long_Lines     On
        Refresh_Interval    5
        storage.type        filesystem
        DB                  /var/log/flb_system.db

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-master.efk-monitoring
        Port            9200
        Logstash_Format On
        Include_Tag_Key On
        HTTP_User       elastic
        HTTP_Passwd     changeme
        Retry_Limit     False

    [OUTPUT]
        Name            es
        Match           host.*
        Host            elasticsearch-master.efk-monitoring
        Port            9200
        Logstash_Format On
        Include_Tag_Key On
        Logstash_Prefix node
        HTTP_User       elastic
        HTTP_Passwd     changeme
        Retry_Limit     False
