apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: efk-monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: "0.20.8"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  valuesFiles:
    - ./infrastructure/fluent-bit/fluent-bit-values.yaml
